#!/usr/bin/env python3
"""The seven std fixed-width integer modules, and the corpus that holds them.

    python3 scripts/fixed-ints/gen.py            # rewrite them
    python3 scripts/fixed-ints/gen.py --check    # are they current?

std/int/i8, i16, i32, u8, u16, u32 and u64 are one design at seven widths
(docs/literal-system-design.md D13, spec 11 "Fixed-width integers"): the
same impls, the same conversions and the same bitwise functions, differing
only in the width, the signedness and U64's unsigned order and division.
Seven hand-maintained copies of one shape drift one copy at a time, and the
drift is invisible to review because each file is plausible on its own. So
the modules are this script's output, and a fix is made here once.

The script also writes scripts/spike-native/fixed_ints.{dawn,expect}. The
expectation is computed here with Python's unbounded integers, from the
definitions (reduce modulo 2^w, read the top bit as a sign for the I types,
truncate `/` and `%`), so it is an opinion from outside Dawn: a wrong rule
both backends shared would still disagree with it. spike-native runs it on
both backends.

`--check` regenerates in memory and compares, with no toolchain, so it
costs well under a second; it runs in the tree-policy job. A module edited
by hand, or this script edited without rerunning it, fails there.
"""

import pathlib
import sys

ROOT = pathlib.Path(__file__).resolve().parent.parent.parent
STD = ROOT / "std"
SPIKE = ROOT / "scripts" / "spike-native"

# ---------------------------------------------------------------- the modules

# The types with a device format, and the name the tile dialect gives it. U16,
# U32 and U64 have none: the dialect has no unsigned integer types, so a
# `Tensor[U32]` should be a type error and not a guess (std/dtype's header).
DTYPES = {"I8": "i8", "I16": "i16", "I32": "i32", "U8": "u8"}

TYPES = [
    ("I8", 8, True), ("I16", 16, True), ("I32", 32, True),
    ("U8", 8, False), ("U16", 16, False), ("U32", 32, False), ("U64", 64, False),
]

def hexs(v):
    return "0x" + format(v, "X")

def module(name, w, signed):
    m = name.lower()
    T = name
    big = (w == 64)
    lo = -(1 << (w - 1)) if signed else 0
    hi = (1 << (w - 1)) - 1 if signed else (1 << w) - 1
    mask = (1 << w) - 1
    kind = "signed" if signed else "unsigned"
    L = []
    a = L.append
    if signed:
        a(f"## Signed {w}-bit integers: `{T}`, an opaque type over `Int` holding")
        a(f"## {lo}..{hi}, with arithmetic that wraps the way `Int`'s does.")
    elif big:
        a("## Unsigned 64-bit integers: `U64`, an opaque type over `Int` that reads")
        a("## the same 64 bits as 0..2^64 - 1, with arithmetic that wraps.")
    else:
        a(f"## Unsigned {w}-bit integers: `{T}`, an opaque type over `Int` holding")
        a(f"## 0..{hi}, with arithmetic that wraps the way `Int`'s does.")
    a("#")
    a("# GENERATED by scripts/fixed-ints/gen.py -- edit there and rerun it; the")
    a("# tree-policy gate fails on a hand edit here.")
    a("#")
    a("# One of seven sibling modules (std/int/i8, i16, i32, u8, u16, u32, u64) that")
    a("# share one shape; docs/literal-system-design.md D13 is the design and spec")
    a("# 11 the contract. Why they are std and not the compiler's: the compiler owns")
    a("# two numbers, Int and Float (D1), and a fixed-width integer is an Int with")
    a("# an invariant, which is what an opaque type is. Measured before this was")
    a("# written: packages/sha2's compression loop over std/int/u32 runs within 1% of")
    a("# the `Int` + `& MASK` form on both backends.")
    a("#")
    a("# They live under std/int/ so that seven of them do not crowd the top of")
    a("# std; `use` binds a path's last segment, so `use std/int/u32` still")
    a("# qualifies as `u32`.")
    a("#")
    a("# Why one module per width and not one module for all seven: a module is")
    a("# Dawn's namespace, so `u32.wrap(n)`, `u32.rotr(x, 7)` and `u8.wrap(n)` are")
    a("# the same names qualified differently, as `char.code` is for `Char`. One")
    a("# module would need either a width in every name (`wrap_u32`) or a trait")
    a("# whose `to_int` member shadows the builtin `to_int` in every importer, and")
    a("# the constructors could not be trait members anyway, since their subject is")
    a("# only in the return position. A program imports the widths it uses.")
    a("#")
    if big:
        a("# U64 has no invariant: every Int is the bit pattern of one U64. Addition,")
        a("# subtraction, multiplication and negation are Int's own, since two's")
        a("# complement wraps the same bits either way. What differs is everything that")
        a("# reads the top bit as a magnitude rather than a sign: `<` (an `impl Ord`")
        a("# of its own, without which a U64 above 2^63 would compare below zero),")
        a("# `/` and `%` (`udiv` below, the derivation `Long.divideUnsigned` uses) and")
        a("# rendering. `to_int` hands back the bit pattern, so a U64 above 2^63 - 1")
        a("# comes out negative; `of` refuses a negative Int for the same reason.")
    else:
        a(f"# The Int inside is always in {lo}..{hi}, so equality, hashing and order")
        a("# are the Int's, inherited (spec 2.7), and correct as they stand: an impl")
        a("# of `Ord` of its own would say the same thing and turn every `<` from a")
        a("# native comparison into a call. Arithmetic is not inherited (an opaque")
        a("# type never inherits it, docs/arith-operator-traits-design.md D4) and is")
        if signed:
            a(f"# written below: each result is computed in Int and wrapped back by")
            a(f"# sign-extending its low {w} bits, so `{T}.MAX + 1` is `{T}.MIN`, as `Int`'s")
            a("# overflow is. `/` and `%` are Int's (truncating, and a zero divisor panics")
            a(f"# with Int's message); the one quotient out of range, MIN / -1, wraps to MIN.")
        else:
            a(f"# written below: each result is computed in Int and wrapped back to its")
            a(f"# low {w} bits, so `0 - 1` is {hi}. `/` and `%` are Int's on non-negative")
            a("# operands, and a zero divisor panics with Int's message.")
    a("#")
    a("# Wrapping and not trapping, as `Int` does (spec 4.3): two overflow rules in")
    a("# one family of types would have every reader looking up which one applies.")
    a("# `checked_add`, `checked_sub` and `checked_mul` answer `None` instead. A")
    a(f"# literal at `{T}` is `FromInt`'s, range-checked at compile time, so")
    a(f"# `let b: {T} = {hi + 1}` does not compile (outside this module: inside it the")
    a("# type is seen through and a literal is the Int it always was, literal design")
    a("# D7). The bitwise operations are named functions until the operators have")
    a("# traits of their own; `complement` and not `not`, which is a keyword. A")
    a(f"# shift or rotation count is taken modulo {w}, as the JVM and the hardware do")
    a("# for Int's own shifts.")
    if T in DTYPES:
        a("#")
        a(f"# `{T}` is also a device format (std/dtype): the constant `{T}` below is its")
        a(f"# witness, spelled like the type so that `use std/int/{m}.{{{T}}}` brings in both,")
        a(f"# and `impl HasDtype[{T}]` lets generic code ask for it by type.")
    a("")
    if T in DTYPES:
        a("use std/dtype.{DeviceBits, Dtype, HasDtype, to_bits, dtype_name, dtype_from_name, dtype_of, from_bits}")
        a("")
    a(f"## A {kind} {w}-bit integer.")
    a(f"pub opaque type {T} = Int")
    a("")
    a(f"## The least `{T}`" + (f", {lo}." if not big else ", 0."))
    a(f"pub const MIN: {T} = {lo if not big else 0}")
    a("")
    if big:
        a("## The greatest `U64`, 2^64 - 1; its bit pattern is the Int -1.")
        a("pub const MAX: U64 = -1")
    else:
        a(f"## The greatest `{T}`, {hi}.")
        a(f"pub const MAX: {T} = {hi}")
    a("")
    if T in DTYPES:
        a(f"## The device format of `{T}`: `{DTYPES[T]}`.")
        a(f"pub const {T}: Dtype[{T}] = dtype_from_name(\"{DTYPES[T]}\")")
        a("")
        a(f"impl HasDtype[{T}] {{")
        a(f"  fn dtype_of() -> Dtype[{T}] = {T}")
        a("}")
        a("")
        a("# The low bits of the two's complement, read unsigned: what a device buffer")
        a("# holds for this element. Bits above the width are ignored on the way back.")
        a(f"impl DeviceBits[{T}] {{")
        a(f"  fn to_bits(v: {T}) -> Int = to_int(v) & 0x{(1 << w) - 1:X}")
        a(f"  fn from_bits(bits: Int) -> {T} = wrap(bits)")
        a("}")
        a("")
    # of / wrap / to_int
    if big:
        a("## `n` as a `U64`, or `None` when `n` is negative: a negative Int is not a")
        a("## number in 0..2^64 - 1. [`wrap`] reads its bits instead.")
        a("pub fn of(n: Int) -> Option[U64] = if n < 0 { None } else { Some(n) }")
        a("")
        a("## The `U64` with the bit pattern of `n`: `wrap(-1)` is [`MAX`].")
        a("pub fn wrap(n: Int) -> U64 = n")
        a("")
        a("## The bit pattern of `x` as an Int: a value above 2^63 - 1 is negative.")
        a("pub fn to_int(x: U64) -> Int = x")
    else:
        a(f"## `n` as a `{T}`, or `None` when it is outside {lo}..{hi}.")
        a(f"pub fn of(n: Int) -> Option[{T}] = if n < {lo} || n > {hi} {{ None }} else {{ Some(n) }}")
        a("")
        if signed:
            a(f"## The `{T}` with the low {w} bits of `n`, read as two's complement:")
            a(f"## `wrap({hi + 1})` is {lo}.")
            a(f"pub fn wrap(n: Int) -> {T} = ((n & {hexs(mask)}) ^ {hexs(1 << (w - 1))}) - {hexs(1 << (w - 1))}")
        else:
            a(f"## The `{T}` with the low {w} bits of `n`: `wrap(-1)` is {hi}.")
            a(f"pub fn wrap(n: Int) -> {T} = n & {hexs(mask)}")
        a("")
        a(f"## The value of `x` as an Int.")
        a(f"pub fn to_int(x: {T}) -> Int = x")
    a("")
    # FromInt
    a("# The literal's range check, run at compile time for every literal at this")
    a("# type outside this module.")
    a(f"impl FromInt[{T}] {{")
    a(f"  fn from_int(n: Int) -> {T} = {{")
    if big:
        a(f'    if n < 0 {{ panic("out of range for U64: ${{n}}") }}')
    else:
        a(f'    if n < {lo} || n > {hi} {{ panic("out of range for {T}: ${{n}}") }}')
    a("    n")
    a("  }")
    a("}")
    a("")
    # Show
    a(f"impl Show[{T}] {{")
    if big:
        a("  fn show(x: U64) -> String = {")
        a("    let n: Int = x")
        a("    if n >= 0 {")
        a("      to_string(n)")
        a("    } else {")
        a("      # the last digit apart, so the rest fits in an Int")
        a("      let q = udiv(n, 10)")
        a("      to_string(q) ++ to_string(n - q * 10)")
        a("    }")
        a("  }")
    else:
        a(f"  fn show(x: {T}) -> String = {{")
        a("    let n: Int = x")
        a("    to_string(n)")
        a("  }")
    a("}")
    a("")
    if big:
        a("impl Ord[U64] {")
        a("  fn cmp(a: U64, b: U64) -> Int = {")
        a("    let x: Int = a")
        a("    let y: Int = b")
        a("    if x == y { 0 } else if ult(x, y) { -1 } else { 1 }")
        a("  }")
        a("}")
        a("")
        a("# Unsigned order on bit patterns: flipping the sign bit of both maps")
        a("# 0..2^64 - 1 onto Int's order.")
        a("fn ult(x: Int, y: Int) -> Bool = (x ^ -9223372036854775808) < (y ^ -9223372036854775808)")
        a("")
        a("# The unsigned quotient. A divisor with its top bit set goes into any")
        a("# dividend at most once. Otherwise halve the dividend so that it is a")
        a("# non-negative Int, divide, double, and correct the estimate, which is at")
        a("# most one short (Hacker's Delight 9-3, as Long.divideUnsigned). A zero")
        a("# divisor reaches Int's `/` and panics with its message.")
        a("fn udiv(n: Int, d: Int) -> Int =")
        a("  if d < 0 {")
        a("    if ult(n, d) { 0 } else { 1 }")
        a("  } else if n >= 0 {")
        a("    n / d")
        a("  } else {")
        a("    let q = ((n >>> 1) / d) << 1")
        a("    if ult(n - q * d, d) { q } else { q + 1 }")
        a("  }")
        a("")
    # arithmetic
    def wrapexpr(e):
        if big:
            return e
        return f"wrap({e})"
    for tr, fn, op in [("Add", "add", "+"), ("Sub", "sub", "-"), ("Mul", "mul", "*")]:
        a(f"impl {tr}[{T}] {{")
        a(f"  fn {fn}(a: {T}, b: {T}) -> {T} = {{")
        a("    let x: Int = a")
        a("    let y: Int = b")
        a(f"    {wrapexpr(f'x {op} y')}")
        a("  }")
        a("}")
        a("")
    for tr, fn, op, uf in [("Div", "div", "/", "udiv(x, y)"), ("Rem", "rem", "%", "x - udiv(x, y) * y")]:
        a(f"impl {tr}[{T}] {{")
        a(f"  fn {fn}(a: {T}, b: {T}) -> {T} = {{")
        a("    let x: Int = a")
        a("    let y: Int = b")
        if big:
            a(f"    {uf}")
        elif signed:
            a(f"    {wrapexpr(f'x {op} y')}")
        else:
            a(f"    x {op} y")
        a("  }")
        a("}")
        a("")
    a(f"impl Neg[{T}] {{")
    a(f"  fn neg(a: {T}) -> {T} = {{")
    a("    let x: Int = a")
    a(f"    {wrapexpr('0 - x')}")
    a("  }")
    a("}")
    a("")
    # checked
    a(f"## `a + b`, or `None` where it wraps.")
    a(f"pub fn checked_add(a: {T}, b: {T}) -> Option[{T}] = {{")
    a("  let x: Int = a")
    a("  let y: Int = b")
    a("  let r = x + y")
    if big:
        a("  if ult(r, x) { None } else { Some(r) }")
    else:
        a(f"  if r < {lo} || r > {hi} {{ None }} else {{ Some(r) }}")
    a("}")
    a("")
    a(f"## `a - b`, or `None` where it wraps.")
    a(f"pub fn checked_sub(a: {T}, b: {T}) -> Option[{T}] = {{")
    a("  let x: Int = a")
    a("  let y: Int = b")
    if big:
        a("  if ult(x, y) { None } else { Some(x - y) }")
    else:
        a("  let r = x - y")
        a(f"  if r < {lo} || r > {hi} {{ None }} else {{ Some(r) }}")
    a("}")
    a("")
    a(f"## `a * b`, or `None` where it wraps.")
    a(f"pub fn checked_mul(a: {T}, b: {T}) -> Option[{T}] = {{")
    a("  let x: Int = a")
    a("  let y: Int = b")
    a("  let r = x * y")
    if big:
        a("  # the product wrapped exactly when dividing it back does not give `b`")
        a("  if x != 0 && udiv(r, x) != y { None } else { Some(r) }")
    elif w == 32 and not signed:
        a("  # a product of two U32s can pass 2^63, where the Int wraps negative,")
        a("  # which the range test below refuses like any other overflow")
        a(f"  if r < {lo} || r > {hi} {{ None }} else {{ Some(r) }}")
    else:
        a(f"  if r < {lo} || r > {hi} {{ None }} else {{ Some(r) }}")
    a("}")
    a("")
    # bitwise
    for fn, op, doc in [("and", "&", "The bitwise and."), ("or", "|", "The bitwise or."), ("xor", "^", "The bitwise exclusive or.")]:
        a(f"## {doc}")
        a(f"pub fn {fn}(a: {T}, b: {T}) -> {T} = {{")
        a("  let x: Int = a")
        a("  let y: Int = b")
        a(f"  x {op} y")
        a("}")
        a("")
    a("## Every bit flipped.")
    a(f"pub fn complement(a: {T}) -> {T} = {{")
    a("  let x: Int = a")
    a(f"  {wrapexpr('~x')}")
    a("}")
    a("")
    k = f"n & {w - 1}"
    a(f"## `a` shifted left by `n` modulo {w} places, zeros in at the bottom.")
    a(f"pub fn shl(a: {T}, n: Int) -> {T} = {{")
    a("  let x: Int = a")
    a(f"  {wrapexpr(f'x << ({k})')}")
    a("}")
    a("")
    if signed:
        a(f"## `a` shifted right by `n` modulo {w} places, copies of the sign bit in at")
        a("## the top (arithmetic, as Int's `>>`).")
        a(f"pub fn shr(a: {T}, n: Int) -> {T} = {{")
        a("  let x: Int = a")
        a(f"  x >> ({k})")
        a("}")
    else:
        a(f"## `a` shifted right by `n` modulo {w} places, zeros in at the top.")
        a(f"pub fn shr(a: {T}, n: Int) -> {T} = {{")
        a("  let x: Int = a")
        a(f"  x >>> ({k})")
        a("}")
    a("")
    for fn, l, r, doc in [("rotl", "<<", ">>>", "left"), ("rotr", ">>>", "<<", "right")]:
        a(f"## `a`'s {w} bits rotated {doc} by `n` modulo {w} places.")
        a(f"pub fn {fn}(a: {T}, n: Int) -> {T} = {{")
        if big:
            a("  let u: Int = a")
        else:
            a(f"  let x: Int = a")
            a(f"  let u = x & {hexs(mask)}")
        a(f"  let k = {k}")
        if big:
            a(f"  (u {l} k) | (u {r} ({w} - k))")
        else:
            a(f"  wrap((u {l} k) | (u {r} ({w} - k)))")
        a("}")
        a("")
    if T in DTYPES:
        a('test "the witness is the format the dialect names, found by value or by type" {')
        a(f"  let by_type: Dtype[{T}] = dtype_of()")
        a(f'  assert dtype_name({T}) == "{DTYPES[T]}"')
        a(f'  assert dtype_name(by_type) == "{DTYPES[T]}"')
        a("}")
        a("")
        mask = f"0x{(1 << w) - 1:X}"
        a(f'test "{T} moves as its low bits, unsigned, and reads back from any word" {{')
        a("  assert to_bits(wrap(1)) == 1")
        a(f"  assert to_bits(MAX) == 0x{hi:X}")
        a(f"  assert to_bits(MIN) == 0x{(1 << (w - 1)) if signed else 0:X}")
        if signed:
            a(f"  assert to_bits(wrap(-1)) == {mask}")
            a(f"  let m: {T} = from_bits({mask})")
            a("  assert m == wrap(-1)")
        a(f"  assert to_int(from_bits({mask} + 1)) == 0")
        a("  # the bits above the width are ignored")
        a(f"  let hi: {T} = from_bits(0x5A5A5A5A5A5A5A5A - (0x5A5A5A5A5A5A5A5A & {mask}) + 3)")
        a("  assert to_int(hi) == 3")
        a("  var n = 0")
        a("  while n < 300 {")
        a(f"    let v: {T} = wrap(n * 7919 - 1000)")
        a(f"    let back: {T} = from_bits(to_bits(v))")
        a("    assert back == v")
        a("    n = n + 1")
        a("  }")
        a("}")
        a("")
    # tests: representative only; scripts/spike-native/fixed_ints is the
    # oracle corpus on both backends
    a("# Representative cases; scripts/spike-native/fixed_ints holds the seven types")
    a("# to an oracle computed outside Dawn, on both backends.")
    a("")
    a('test "the ends wrap into each other and the conversions agree" {')
    a("  assert MAX + wrap(1) == MIN")
    a("  assert MIN - wrap(1) == MAX")
    a("  assert to_int(wrap(7) / wrap(2)) == 3")
    a("  assert to_int(wrap(7) % wrap(2)) == 1")
    a(f"  assert rotl(wrap(1), {w}) == wrap(1)")
    a(f"  assert rotr(wrap(1), 1) == shl(wrap(1), {w - 1})")
    a("  assert checked_add(MAX, wrap(1)) == None")
    a("  assert checked_sub(MIN, wrap(1)) == None")
    if big:
        a("  assert of(-1) == None")
        a("  assert to_int(MAX) == -1")
        a('  assert show(MAX) == "18446744073709551615"')
        a("  # the order is unsigned: the top bit is a magnitude, not a sign")
        a("  assert wrap(0) < MAX")
        a("  assert to_int(MAX / wrap(10)) == 1844674407370955161")
        a("  assert to_int(MAX % wrap(10)) == 5")
    else:
        a(f"  assert of({hi + 1}) == None")
        a(f"  assert of({lo}) == Some(MIN)")
        a(f"  assert to_int(wrap({hi + 1})) == {lo}")
        a(f'  assert show(MIN) == "{lo}"')
        if signed:
            a("  # the one quotient out of range wraps, as Int's MIN / -1 does")
            a("  assert MIN / wrap(-1) == MIN")
            a("  assert to_int(shr(MIN, 1)) == " + str(lo // 2))
        else:
            a(f"  assert to_int(-wrap(1)) == {hi}")
            a(f"  assert to_int(complement(MIN)) == {hi}")
    a("}")
    a("")
    return "\n".join(L)


# ---------------------------------------------------------------- the corpus

def rng(w, s):
    return (-(1 << (w-1)), (1 << (w-1)) - 1) if s else (0, (1 << w) - 1)

def wrap(v, w, s):
    v &= (1 << w) - 1
    if s and v >= 1 << (w-1):
        v -= 1 << w
    return v

def tdiv(a, b):  # truncating, as Int's / (operands here never overflow Int)
    q = abs(a) // abs(b)
    return q if (a < 0) == (b < 0) else -q

def trem(a, b):
    return a - tdiv(a, b) * b

def pairs(w, s):
    lo, hi = rng(w, s)
    ps = [(hi, 1), (lo, 1), (lo, hi), (hi, hi), (7, 3), (100, 7)]
    if s:
        ps += [(lo, -1), (-7, 3), (7, -3), (-7, -3), (-1, hi)]
    else:
        ps += [(hi, 2), (hi - 5, hi), (1, hi), (hi // 2 + 3, 2)]
    out = []
    for a, b in ps:
        a = max(lo, min(hi, a)); b = max(lo, min(hi, b))
        if b != 0:
            out.append((a, b))
    return out

def lit(v, name, w, s):
    """A Dawn expression of type T with value v."""
    m = name.lower()
    if w == 64 and v > (1 << 63) - 1:
        return f"{m}.wrap({v - (1 << 64)})"
    return f"{m}_({v})"

def show(v):
    return str(v)

def checked(v, w, s):
    lo, hi = rng(w, s)
    return f"Some({v})" if lo <= v <= hi else "None"

def corpus():
    prog = []
    exp = []
    P = prog.append
    P("# GENERATED by scripts/fixed-ints/gen.py -- do not edit by hand.")
    P("#")
    P("# Fixed-width integers in std (docs/literal-system-design.md D13): the seven")
    P("# types' wrapping arithmetic, through a generic function (so dictionaries)")
    P("# and directly, their bitwise functions, the checked forms, order, rendering")
    P("# and the conversions, on both backends. The operands are literals at each")
    P("# type, folded through FromInt at compile time; a U64 above 2^63 - 1 has no")
    P("# literal and is `u64.wrap` of its bit pattern.")
    P("#")
    P("# fixed_ints.expect is not recorded from a backend: it was computed with")
    P("# Python's unbounded integers from the definitions (reduce modulo 2^w, read")
    P("# the top bit as a sign for the I types; `/` and `%` truncate), so a wrong")
    P("# rule shared by both backends would still disagree with it.")
    for name, w, s in TYPES:
        P(f"use std/int/{name.lower()}")
    P("")
    P("fn arith[T: Add + Sub + Mul + Div + Rem + Neg + Show + Ord + Eq](a: T, b: T) -> String !(T.Add | T.Sub | T.Mul | T.Div | T.Rem | T.Neg) =")
    P('  "${show(a + b)} ${show(a - b)} ${show(a * b)} ${show(a / b)} ${show(a % b)} ${show(-a)} ${a < b} ${a == b}"')
    P("")
    P("fn opt[T: Show](o: Option[T]) -> String =")
    P("  match o {")
    P('    Some(v) -> "Some(${show(v)})"')
    P('    None -> "None"')
    P("  }")
    P("")
    for name, w, s in TYPES:
        m = name.lower()
        P(f"fn {m}_(x: {m}.{name}) -> {m}.{name} = x")
        P("")
    main = ["pub fn main() -> Unit !io = {"]
    M = main.append
    for name, w, s in TYPES:
        m = name.lower()
        lo, hi = rng(w, s)
        M(f'  println("-- {m} --")')
        exp.append(f"-- {m} --")
        M(f'  println("${{show({m}.MIN)}} ${{show({m}.MAX)}}")')
        exp.append(f"{lo} {hi}")
        for a, b in pairs(w, s):
            A = lit(a, name, w, s); B = lit(b, name, w, s)
            M(f'  println("{a} {b}: " ++ arith({A}, {B}))')
            r = [wrap(a + b, w, s), wrap(a - b, w, s), wrap(a * b, w, s), wrap(tdiv(a, b), w, s),
                 wrap(trem(a, b), w, s), wrap(-a, w, s)]
            exp.append(f"{a} {b}: " + " ".join(map(str, r)) + f" {'true' if a < b else 'false'} {'true' if a == b else 'false'}")
            # direct operators (concrete impl, devirtualised) must agree
            M(f'  println(show({A} + {B} * {B} - -{A}))')
            exp.append(str(wrap(a + wrap(b * b, w, s) - wrap(-a, w, s), w, s)))
            k = 3
            mask = (1 << w) - 1
            ua, ub = a & mask, b & mask
            bits = [wrap(ua & ub, w, s), wrap(ua | ub, w, s), wrap(ua ^ ub, w, s), wrap(~a, w, s),
                    wrap(ua << k, w, s), (a >> k) if s else (ua >> k),
                    wrap(((ua << k) | (ua >> (w - k))) & mask, w, s),
                    wrap(((ua >> k) | (ua << (w - k))) & mask, w, s),
                    wrap(ua << ((w + 1) & (w - 1)), w, s)]
            M(f'  println("${{show({m}.and({A}, {B}))}} ${{show({m}.or({A}, {B}))}} ${{show({m}.xor({A}, {B}))}} ${{show({m}.complement({A}))}} '
              f'${{show({m}.shl({A}, {k}))}} ${{show({m}.shr({A}, {k}))}} ${{show({m}.rotl({A}, {k}))}} ${{show({m}.rotr({A}, {k}))}} ${{show({m}.shl({A}, {w + 1}))}}")')
            exp.append(" ".join(map(str, bits)))
            M(f'  println("${{opt({m}.checked_add({A}, {B}))}} ${{opt({m}.checked_sub({A}, {B}))}} ${{opt({m}.checked_mul({A}, {B}))}}")')
            exp.append(f"{checked(a + b, w, s)} {checked(a - b, w, s)} {checked(a * b, w, s)}")
        # conversions
        probes = [lo - 1, lo, hi, hi + 1, -1, 300] if w < 64 else [-1, 0, (1 << 63) - 1]
        for n in probes:
            if not (-(1 << 63) <= n < (1 << 63)):
                continue
            M(f'  println("{n}: ${{opt({m}.of({n}))}} ${{show({m}.wrap({n}))}} ${{{m}.to_int({m}.wrap({n}))}}")')
            ok = lo <= n <= hi if w < 64 else n >= 0
            wv = wrap(n, w, s)
            ti = wv if w < 64 else (wv - (1 << 64) if wv >= 1 << 63 else wv)
            exp.append(f"{n}: {'Some(' + str(n) + ')' if ok else 'None'} {wv} {ti}")
        # order and sort through the type's own Ord (U64's top bit)
        xs = [hi, lo, 1, hi // 3]
        M(f'  println("${{show(sort([{", ".join(lit(x, name, w, s) for x in xs)}]))}}")')
        exp.append("[" + ", ".join(map(str, sorted(xs))) + "]")
    M("}")
    return "\n".join(prog + main) + "\n", "\n".join(exp) + "\n"


# ---------------------------------------------------------------- driver


def outputs() -> dict:
    out = {}
    for name, w, signed in TYPES:
        out[STD / "int" / f"{name.lower()}.dawn"] = module(name, w, signed)
    program, expect = corpus()
    out[SPIKE / "fixed_ints.dawn"] = program
    out[SPIKE / "fixed_ints.expect"] = expect
    return out


def main(argv: list) -> int:
    files = outputs()
    if argv[1:] == ["--check"]:
        stale = [p for p, text in files.items() if not p.exists() or p.read_text() != text]
        for p in stale:
            print(f"STALE {p.relative_to(ROOT)}: not what scripts/fixed-ints/gen.py generates", file=sys.stderr)
        if stale:
            print("rerun: python3 scripts/fixed-ints/gen.py", file=sys.stderr)
            return 1
        print(f"OK   {len(files)} fixed-width files match their generator")
        return 0
    if argv[1:]:
        print("usage: gen.py [--check]", file=sys.stderr)
        return 2
    for p, text in files.items():
        p.write_text(text)
    print(f"wrote {len(files)} files")
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv))
