#!/usr/bin/env bash
# K-A7 (docs/jvm-base-plan.md §5.7): the `dawn/rt/Asm` the compiler emits must
# be a drop-in for the five `dawn.tool.AdtClassWriter` statics that used to be
# the last handwritten Java in the trusted base (BOOT-01).
#
#   ./scripts/asm-adapter-contract/run.sh
#
# K-A8.1 added the other half of the same reference: `dawn/rt/AsmWriter`, the
# `ClassWriter` subclass that answers the common-superclass question frame
# computation asks. Nothing in the compiler calls it -- V49 computes no frames
# -- so it is in exactly the position `dawn/rt/Asm` was in during phase 1: every
# other gate is green whatever it contains. It rides here because it is emitted
# by the same three adapters (`plain`/`beginOn`/`methodOn`) and answers to the
# same archived reference, so the class-path shadow below decouples it too.
#
# In phase 1 nothing called the emitted class, so every other gate was green
# whatever `gen_asm_class` wrote, including nothing at all. Since phase 2 the
# call sites name it -- and the reason this gate still matters is the mirror
# image: the two adapters are interchangeable, so nothing else could tell a
# compiler that migrated from one that did not (scripts/adapter-callsites.py
# is the check for that half).
#
# ---------------------------------------------------------------------------
# The invariant this gate exists to hold, and which nothing else states
# ---------------------------------------------------------------------------
#
# Since phase 2 `gen_asm_class` writes the adapter *with* the adapter: the five
# statics emit themselves, generation after generation. That is ordinary
# compiler bootstrapping, and it also reproduces Thompson's attack at small
# scale. A sufficiently careful wrong adapter emits an equally wrong adapter;
# the result loads, behaves consistently with itself, keeps `selfhost-fixpoint`
# at B == C (a fixpoint reproduces a substituted compiler just as faithfully as
# an honest one) and keeps `scripts/adapter-callsites.py` green (it counts
# constant-pool references, not semantics). BOOT-01's threat model did not go
# away when the 5,148-byte vendored binary did; it moved onto a 1,225-byte
# self-emitted class.
#
# What stands against it is one link, here, and only here: **the reference is
# compiled by javac from the Java source archived in the `kotlin-final` tag.**
# That is the single step in the whole chain that does not pass through the
# Dawn compiler, which is what makes this a diverse-double-compiling argument
# rather than a tautology. Three things therefore must not change:
#
#   1. The reference must keep being built by a *different* toolchain (javac)
#      from the *archived* source. Not read out of a jar we built, not
#      regenerated by us.
#   2. This gate must not be changed to compare the emitted class against
#      itself, against a checked-in golden copy of it, or against anything else
#      our own build produced. Every one of those still passes every check
#      below while proving nothing -- the DDC property would evaporate in
#      silence, which is the repo's governing failure mode.
#   3. The tagged source must not be copied into the working tree "to remove
#      the dependency on a tag". A working-tree copy is a file our own commits
#      can edit; the point of the tag is that the reference is fixed history.
#      That refactor looks like hardening and is the exact opposite.
#
# `git fetch` of the tag failing is the *lucky* outcome: it is loud. The
# dangerous edits are the ones that leave this script green.
#
# How much of that is machine-checked, exactly (§5.7 has the red demos):
#
#   (2) yes -- Diff.java's `referenceIsForeign` asserts the reference still
#       carries the members this compiler does not emit, so a reference that
#       became our own artifact fails. Repoint it at the emitted class and all
#       fourteen differential checks still pass; only that one goes red.
#   (3) yes -- the guard below, for a Java copy landing in the tree.
#   (1) only in part. (2) proves the reference is not something we built, not
#       that it came from *this* tag; an identical javac build from somewhere
#       else would satisfy it. (3) closes the one concrete way that happens.
#
# No gate can assert its own independence -- all three checks are one delete
# away from gone, and nothing detects that. The prose above is not decoration;
# it is the part of the mitigation a machine cannot carry.
#
# Red demo (2026-08-04): see docs/jvm-base-plan.md §5.7. Every check below has
# been shown to go red, each against a discriminating negative control.
set -euo pipefail
cd "$(dirname "$0")/../.."
root=$(pwd)

REF_SRC=compiler/src/main/java/dawn/tool/AdtClassWriter.java
REF_TAG=kotlin-final

# Invariant 3, by machine. This catches the specific refactor named above: a
# Java copy of the reference landing in the tree, at the tagged path or any
# other. It does not catch a copy under a different class name, and it cannot
# catch someone deleting this check -- see the header.
if [ -e "$REF_SRC" ] || [ -n "$(git grep -l -e 'class AdtClassWriter' -- '*.java' || true)" ]; then
  echo "FAIL  the reference source must live only in the $REF_TAG tag" >&2
  echo "      found a working-tree copy; see the invariant in $0" >&2
  exit 1
fi
echo "PASS  the reference source is not in the working tree"

./bin/dawn --version > /dev/null

work="$(mktemp -d)"
trap 'rm -rf "$work"' EXIT

# The reference, rebuilt from the tagged Java source by javac. A fresh CI
# checkout is shallow and tagless, so fetch the tag before asking for it (the
# same shape seedjar.sh uses for the seed's std).
git rev-parse -q --verify "refs/tags/$REF_TAG" > /dev/null ||
  git fetch -q --depth 1 origin tag "$REF_TAG"
mkdir -p "$work/ref"
git show "$REF_TAG:$REF_SRC" > "$work/ref/AdtClassWriter.java"
javac -nowarn -cp "$root/build/dawn-selfhost.jar" -d "$work/ref" "$work/ref/AdtClassWriter.java"

# The same tagged source again, repackaged as `dawn.rt.Asm` so it can stand in
# for the emitted adapter on the compiler's own class path. Only the package
# and the class name change; the five statics are the tag's, byte for byte the
# same javac output.
#
# This is what breaks the self-application. `gen_asm_class` calls
# `Asm.plain`/`beginOn`/`methodOn` while writing the class that defines them, so
# a defect in those three corrupts the emitter at the same moment it corrupts
# the emitted bytes -- and the product is malformed rather than merely wrong, so
# the differential below cannot say which entry point broke. Put the javac build
# first on the class path and the emitter is the reference while the bytes are
# still whatever today's `gen_asm_class` writes. Five-way discrimination comes
# back, and the emission is now one javac step removed from the compiler under
# test.
mkdir -p "$work/shadow-src/dawn/rt" "$work/shadow"
sed -e 's/^package dawn\.tool;/package dawn.rt;/' -e 's/\bAdtClassWriter\b/Asm/g' \
  "$work/ref/AdtClassWriter.java" > "$work/shadow-src/dawn/rt/Asm.java"
javac -nowarn -cp "$root/build/dawn-selfhost.jar" -d "$work/shadow" \
  "$work/shadow-src/dawn/rt/Asm.java"

# The canary: the same stand-in with `plain` refusing to forward its flag. A
# class-path shadow that is not actually in effect is invisible -- both
# emissions would come out identical and every check would stay green while the
# decoupling silently did nothing. That is the shape `scripts/classfile-verify`
# was found in on 2026-08-03. So the gate carries its own mutant and asserts
# every run that the doctored adapter changes what comes out.
mkdir -p "$work/canary-src/dawn/rt" "$work/canary"
sed -e 's/return new ClassWriter(flags);/return new ClassWriter(0);/' \
  "$work/shadow-src/dawn/rt/Asm.java" > "$work/canary-src/dawn/rt/Asm.java"
javac -nowarn -cp "$root/build/dawn-selfhost.jar" -d "$work/canary" \
  "$work/canary-src/dawn/rt/Asm.java"

# The emitted class comes from the compiler's own emission, not from a copy
# checked in here: what is under test is what `dawn build selfhost` puts in the
# jar. `selfhost` is the corpus that has ASM on its class path, which is the
# condition main.dawn emits `dawn/rt/Asm` under.
#
# `main` is the jar's Main-Class; `-cp` rather than `-jar` because the shadow
# has to precede the jar, and `-jar` ignores `-cp`. Subject 1 uses no shadow, so
# it is exactly what bin/dawn ships.
emit() { # emit <outdir> <prefix-of-classpath-or-empty>
  mkdir -p "$1"
  java -Xss512m -cp "${2:+$2:}$root/build/dawn-selfhost.jar" main \
    __emit selfhost -o "$1" > /dev/null
  for c in Asm AsmWriter; do
    if [ ! -f "$1/dawn/rt/$c.class" ]; then
      echo "FAIL: the compiler emitted no dawn/rt/$c for the selfhost corpus" >&2
      exit 1
    fi
  done
}
emit "$work/self" ""
emit "$work/ddc" "$work/shadow"
emit "$work/canary-emit" "$work/canary"

javac -cp "$root/build/dawn-selfhost.jar" -d "$work" scripts/asm-adapter-contract/Diff.java
# The emitted directories are deliberately *not* on the class path: Diff reads
# those class files as bytes and defines each in its own loader, so there is no
# question about which `dawn.rt.Asm` a check looked at.
java -cp "$work:$work/ref:$root/build/dawn-selfhost.jar" Diff \
  "$work/self/dawn/rt/Asm.class" \
  "$work/ddc/dawn/rt/Asm.class" \
  "$work/canary-emit/dawn/rt/Asm.class" \
  "$work/self/dawn/rt/AsmWriter.class" \
  "$work/ddc/dawn/rt/AsmWriter.class"
